# Generated by Django 3.0.6 on 2020-06-01 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('photo', models.ImageField(blank=True, upload_to='static/product_photo')),
                ('basic_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('standard_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('premium_price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
